module.exports = {
  NO_VERSION_STATIC_CDN_PREFIX: '/',
  HOST_DOMAIN: 'tujia.com',
  TUJIA_DOMAIN: 'dev.tujia.com',
  PASSPORT_TUJIA_HOST: 'http://passport.dev.tujia.com',
  STATICFILE_TUJIA_HOST: 'http://staticfile.dev.tujia.com',
  PIC_TUJIA_HOST: 'https://pic1.fvt.tujia.com',
  PWA_TUJIA_HOST: 'https://pwa.dev.tujia.com',
  UPLOAD_TUJIA_HOST: 'https://upload.fvt.tujia.com',
  TNS_DOMAIN: 'http://10.2.98.213:8080',
  ASSIGN_DOMAIN: 'http://assign.fvt.tujia.com',
  OPERATE_DOMAIN: 'https://nedit.fvt.tujia.com',
  HOUSE_DOMAIN: 'https://www1.fvt.tujia.com',
  NCC_TUJIA_HOST: 'https://ncc.dev.tujia.com',
  CHATBOT_TUJIA_HOST: 'http://chatbot.dev.tujia.com',
  WS_CHATBOT_TUJIA_HOST: 'ws://chatbot.dev.tujia.com',
  PROVIDERCRM_TUJIA_HOST: 'http://providercrm.dev.tujia.com:8080',
  FELOG_TUJIA_HOST: 'http://felog.dev.tujia.com',
  MINI_PROGRAM_TYPE: 2,
  MINI_SAMLLAPP_APPID: 'gh_77aae4e7b992',
  GUANJIA_TUJIA_HOST: 'https://guanjia.dev.tujia.com',
  CHATSERVICE_TUJIA_HOST: 'http://chatservice.dev.tujia.com',
  CS_TUJIA_HOST: 'http://cs.dev.tujia.com',
  OLD_ASSIGN_HOST: 'https://order2.dev.tujia.com'
}
