module.exports = {
  NO_VERSION_STATIC_CDN_PREFIX: '/',
  HOST_DOMAIN: 'tujia.com',
  TUJIA_DOMAIN: 'fvt.tujia.com',
  PASSPORT_TUJIA_HOST: 'https://passport2.fvt.tujia.com',
  STATICFILE_TUJIA_HOST: 'https://staticfile2.fvt.tujia.com',
  PIC_TUJIA_HOST: 'https://pic2.fvt.tujia.com',
  PWA_TUJIA_HOST: 'https://pwa2.fvt.tujia.com',
  UPLOAD_TUJIA_HOST: 'https://upload.fvt.tujia.com',
  TNS_DOMAIN: 'https://tnscallcenterapi2.fvt.tujia.com',
  ASSIGN_DOMAIN: 'http://assign2.fvt.tujia.com',
  OPERATE_DOMAIN: 'https://nedit2.fvt.tujia.com',
  HOUSE_DOMAIN: 'https://www2.fvt.tujia.com',
  NCC_TUJIA_HOST: 'https://ncc2.fvt.tujia.com',
  CHATBOT_TUJIA_HOST: 'https://chatbot2.fvt.tujia.com',
  WS_CHATBOT_TUJIA_HOST: 'wss://chatbot2.fvt.tujia.com',
  PROVIDERCRM_TUJIA_HOST: 'https://providercrm2.fvt.tujia.com',
  FELOG_TUJIA_HOST: 'https://felog.fvt.tujia.com',
  MINI_PROGRAM_TYPE: 2,
  MINI_SAMLLAPP_APPID: 'gh_77aae4e7b992',
  GUANJIA_TUJIA_HOST: 'https://guanjia2.fvt.tujia.com',
  CHATSERVICE_TUJIA_HOST: 'http://chatservice2.fvt.tujia.com',
  CS_TUJIA_HOST: 'https://cs2.fvt.tujia.com',
  OLD_ASSIGN_HOST: 'https://order2.fvt.tujia.com'
}
