module.exports = {
  NO_VERSION_STATIC_CDN_PREFIX: '/',
  HOST_DOMAIN: 'tujia.com',
  TUJIA_DOMAIN: 'fvt.tujia.com',
  PASSPORT_TUJIA_HOST: 'https://passport.fvt.tujia.com',
  STATICFILE_TUJIA_HOST: 'https://staticfile.fvt.tujia.com',
  PIC_TUJIA_HOST: 'https://pic.fvt.tujia.com',
  UPLOAD_TUJIA_HOST: 'https://upload.fvt.tujia.com',
  PWA_TUJIA_HOST: 'https://pwa.fvt.tujia.com',
  TNS_DOMAIN: 'https://tnscallcenterapi.fvt.tujia.com',
  ASSIGN_DOMAIN: 'http://assign.fvt.tujia.com',
  OPERATE_DOMAIN: 'https://nedit.fvt.tujia.com',
  HOUSE_DOMAIN: 'https://www.fvt.tujia.com',
  PROVIDERCRM_TUJIA_HOST: 'https://providercrm.fvt.tujia.com',
  FELOG_TUJIA_HOST: 'https://felog.fvt.tujia.com',
  MINI_PROGRAM_TYPE: 2,
  MINI_SAMLLAPP_APPID: 'gh_77aae4e7b992',
  GUANJIA_TUJIA_HOST: 'https://guanjia.fvt.tujia.com',
  CHATSERVICE_TUJIA_HOST: 'http://chatservice.fvt.tujia.com',
  CS_TUJIA_HOST: 'https://cs.fvt.tujia.com',
  OLD_ASSIGN_HOST: 'https://order.fvt.tujia.com'
}
