module.exports = {
  NO_VERSION_STATIC_CDN_PREFIX: '/',
  HOST_DOMAIN: 'tujia.com',
  TUJIA_DOMAIN: 'tujia.com',
  PASSPORT_TUJIA_HOST: 'https://passport.tujia.com',
  STATICFILE_TUJIA_HOST: 'https://staticfile.tujia.com',
  PIC_TUJIA_HOST: 'https://pic.tujia.com',
  PWA_TUJIA_HOST: 'https://pwa.tujia.com',
  UPLOAD_TUJIA_HOST: 'https://upload.tujia.com',
  TNS_DOMAIN: 'https://tnscallcenterapi.tujia.com',
  ASSIGN_DOMAIN: 'http://assign.tujia.com',
  OPERATE_DOMAIN: 'https://nedit.tujia.com',
  HOUSE_DOMAIN: 'https://www.tujia.com',
  CHATBOT_TUJIA_HOST: 'https://chatbot.tujia.com',
  WS_CHATBOT_TUJIA_HOST: 'wss://chatbot.tujia.com',
  PROVIDERCRM_TUJIA_HOST: 'https://providercrm.tujia.com',
  FELOG_TUJIA_HOST: 'https://felog.tujia.com',
  MINI_PROGRAM_TYPE: 0,
  MINI_SAMLLAPP_APPID: 'gh_8e5bfcfff118',
  GUANJIA_TUJIA_HOST: 'https://guanjia.tujia.com',
  CHATSERVICE_TUJIA_HOST: 'http://chatservice.tujia.com',
  CS_TUJIA_HOST: 'https://cs.tujia.com',
  OLD_ASSIGN_HOST: 'https://order.tujia.com'
}
